### ISSUE TITLE
As a student i want to be able to insert my ingredients

### ISSUE THREAD

**Issue by LeanderCoevoet** [bvwman/ScrumExcercise#5]
AcceptatieCriteria
Een veld voor een ingedrienten
Er is een zoek knop
Er kunnen meer dan 1 ingedrient ingeven
Je kan er maximum 5 ingedrienten ingeven
Een aangename landing page voor ingeven van ingedrienten

ESTIMATE
3

**Comment by BelgianCrowbar** [comment]
Backend: Domain,  🥉 
Frontend: JSP, Simple CSS 🥉
